### ISSUE TITLE
The code of lexical-patch alignment visualization

### ISSUE THREAD

**Issue by jiyt17** [guilk/VLC#3]
Hello, I want to visualize lexical-patch alignment. So which layer's cross-attention map I should use? May you release the code of visualization? Thank you!

**Comment by guilk** [comment]
Hi, I upload the code to reproduce our results of Figure 5 and 6. Sorry that I have not cleaned up the code so you have to change some paths by yourself. Please check [visualize_vlc.py](https://github.com/guilk/VLC/blob/main/visualizations/visualize_vlc.py)

**Comment by jiyt17** [comment]
OK, thank you.
