### ISSUE TITLE
What is the image resolution for VQA finetuning 384 x 384 like the pretraining?

### ISSUE THREAD

**Issue by sanyalsunny111** [guilk/VLC#6]

**Comment by guilk** [comment]
For VQA finetuning, I use 576x576 following METER paper. But it has a marginal improvement over 480x480. Both work better than 384x384.

**Comment by sanyalsunny111** [comment]
I am a bit confused how did you pretrain on 384 x 384 and then finetune on a different resolution? Did you change the positional encoding like ViT does if yes please point to that part of the code. If not What extra you added in the fine-tune code for fine-tuning on a different resolution?

**Comment by guilk** [comment]
Check https://github.com/guilk/VLC/blob/ab05438e539c6a08454cbf9b84934814e6ed4452/vlc/modules/objectives.py#L645
